using Microsoft.Extensions.DependencyInjection;
using XrmPluginCore.Enums;
using XrmPluginCore.Tests.Context.BusinessDomain;


// Import the generated PreImage/PostImage from the namespace
using XrmPluginCore.Tests.TestPlugins.TypeSafe.PluginRegistrations.TypeSafeAccountPlugin.AccountUpdatePreOperation;

namespace XrmPluginCore.Tests.TestPlugins.TypeSafe;

/// <summary>
/// Test plugin using the type-safe image API.
/// PreImage and PostImage wrappers are generated by the source generator
/// and passed directly to the action callback.
/// </summary>
public class TypeSafeAccountPlugin : Plugin
{
	public bool UpdateExecuted { get; private set; }
	public PreImage LastPreImage { get; private set; }
	public PostImage LastPostImage { get; private set; }

	public TypeSafeAccountPlugin()
	{
		// Type-safe API: Images are passed directly to the action via source-generated wrapper
		RegisterStep<Account, TypeSafeAccountService>(EventOperation.Update, ExecutionStage.PreOperation,
			nameof(TypeSafeAccountService.HandleUpdate))
			.AddFilteredAttributes(x => x.Name, x => x.AccountNumber)
			.WithPreImage(x => x.Name, x => x.AccountNumber, x => x.Revenue)
			.WithPostImage(x => x.Name, x => x.AccountNumber);
	}

	protected override IServiceCollection OnBeforeBuildServiceProvider(IServiceCollection services)
	{
		services.AddScoped(_ => new TypeSafeAccountService(this));
		return base.OnBeforeBuildServiceProvider(services);
	}

	internal void SetExecutionResult(PreImage preImage, PostImage postImage)
	{
		UpdateExecuted = true;
		LastPreImage = preImage;
		LastPostImage = postImage;
	}
}
