using Microsoft.Extensions.DependencyInjection;
using Microsoft.Xrm.Sdk;
using XrmPluginCore.Enums;

// Import the generated PreImage from the namespace
using XrmPluginCore.Tests.TestPlugins.TypeSafe.PluginRegistrations.TypeSafeContactPlugin.ContactCreatePostOperation;

namespace XrmPluginCore.Tests.TestPlugins.TypeSafe;

/// <summary>
/// Test plugin using the type-safe image API.
/// PreImage wrapper is generated by the source generator
/// and passed directly to the action callback.
/// </summary>
public class TypeSafeContactPlugin : Plugin
{
	public bool CreateExecuted { get; private set; }
	public PreImage LastPreImage { get; private set; }

	public TypeSafeContactPlugin()
	{
		// Type-safe API: PreImage is passed directly to the action via source-generated wrapper
		RegisterStep<Contact, TypeSafeContactService>(EventOperation.Create, ExecutionStage.PostOperation,
			nameof(TypeSafeContactService.HandleCreate))
			.AddFilteredAttributes(x => x.Firstname, x => x.Lastname, x => x.Emailaddress1)
			.WithPreImage(x => x.Firstname, x => x.Lastname, x => x.Mobilephone);
	}

	protected override IServiceCollection OnBeforeBuildServiceProvider(IServiceCollection services)
	{
		services.AddScoped(_ => new TypeSafeContactService(this));
		return base.OnBeforeBuildServiceProvider(services);
	}

	internal void SetExecutionResult(PreImage preImage)
	{
		CreateExecuted = true;
		LastPreImage = preImage;
	}
}

/// <summary>
/// Simple Contact entity class for testing
/// </summary>
public class Contact : Entity
{
	public Contact() : base("contact") { }

	[AttributeLogicalName("firstname")]
	public string Firstname
	{
		get => GetAttributeValue<string>("firstname");
		set => SetAttributeValue("firstname", value);
	}

	[AttributeLogicalName("lastname")]
	public string Lastname
	{
		get => GetAttributeValue<string>("lastname");
		set => SetAttributeValue("lastname", value);
	}

	[AttributeLogicalName("emailaddress1")]
	public string Emailaddress1
	{
		get => GetAttributeValue<string>("emailaddress1");
		set => SetAttributeValue("emailaddress1", value);
	}

	[AttributeLogicalName("mobilephone")]
	public string Mobilephone
	{
		get => GetAttributeValue<string>("mobilephone");
		set => SetAttributeValue("mobilephone", value);
	}
}
